

## SERVIDOR
server:
  port: 8083
  compression:
    enabled: true
  error:
    include-stacktrace: never
  servlet:
    context-path: /

## APLICACION
spring:
  main:
     allow-bean-definition-overriding: true
  application:
    name: imd-user-register        
    version: v1.0.0
    restPort: ${server.port}
  messages:
    encoding: UTF-8  

#Database
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017      
      authentication-database: admin
      database: imd      
      repositories:
        type: reactive


## APPLICATION
application:
  log: /logs/
  ##secret and salt for encrypt or decrypt information. 
  secret: 763Inkjjht3gr4t10n$
  salt: Db3.*3Y^8"x'\Hdv
  password-validation-regex: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{8,}$
  services:
    ping: /ping
    # API's
    user-crud: /api/v1/user-register/
  login-tries: 5
  #Blocking time in minutes
  account-blocking-time: 1 
  system-profile-name: pruebas


    
## LOGGGER
logging:
  level:
    root: INFO
    org.springframework: INFO
    co.com.aruma: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss:SSS} [%5p] [%t] - %15c{1}:[%4L] - %m%n"
